apiVersion: v2
appVersion: 2.12.4
description: A Helm chart for the NATS.io High Speed Cloud Native Distributed Communications Technology.
name: nats
keywords:
- nats
- messaging
- cncf
version: 2.12.4
home: http://github.com/nats-io/k8s
maintainers:
- email: info@nats.io
  name: The NATS Authors
  url: https://github.com/nats-io
icon: https://nats.io/img/nats-icon-color.png
dependencies:
  - name: nats-s3
    version: 0.1.0
    repository: "oci://ghcr.io/ashupednekar/charts"
    condition: s3.enabled

