---
apiVersion: v2
appVersion: 2.9.0
description: A Helm chart for the NATS.io High Speed Cloud Native Distributed Communications
  Technology.
name: nats
keywords:
- nats
- messaging
- cncf
version: 0.18.0
home: http://github.com/nats-io/k8s
maintainers:
- name: Waldemar Quevedo
  url: https://github.com/wallyqs
  email: wally@nats.io
- name: Colin Sullivan
  url: https://github.com/ColinSullivan1
  email: colin@nats.io
- name: Jaime Pi√±a
  url: https://github.com/nsurfer
  email: jaime@nats.io
- name: Caleb Lloyd
  url: https://github.com/caleblloyd
  email: caleb@nats.io
icon: https://nats.io/img/nats-icon-color.png
