version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
- package-ecosystem: docker
  directory: /helm/charts/nack
  schedule:
    interval: daily
  cooldown:
    default-days: 7
- package-ecosystem: docker
  directory: /helm/charts/nats-kafka
  schedule:
    interval: daily
  cooldown:
    default-days: 7
- package-ecosystem: docker
  directory: /helm/charts/nats-operator
  schedule:
    interval: daily
  cooldown:
    default-days: 7
- package-ecosystem: docker
  directory: /helm/charts/nats
  schedule:
    interval: daily
  cooldown:
    default-days: 7
- package-ecosystem: docker
  directory: /helm/charts/surveyor
  schedule:
    interval: daily
  cooldown:
    default-days: 7
