apiVersion: v2
appVersion: "1.0.0"
description: A Helm chart for the NATS.io JWT Account Server
name: nats-account-server
keywords:
- nats
- messaging
- cncf
- jwt
- auth
version: 0.8.1
home: http://github.com/nats-io/k8s
maintainers:
- email: info@nats.io
  name: The NATS Authors
  url: https://github.com/nats-io
icon: https://nats.io/img/nats-icon-color.png
