apiVersion: v2
name: surveyor
description: NATS Monitoring, Simplified.
type: application
version: 0.20.6
appVersion: 0.9.7
maintainers:
  - email: info@nats.io
    name: The NATS Authors
    url: https://github.com/nats-io
