apiVersion: v2
appVersion: "0.18.0"
description: A Helm chart for NATS Streaming
name: stan
keywords:
  - nats
  - streaming
  - stan
  - delivery
  - ratelimit
  - replay
  - statefulset
  - cncf
version: 0.5.4
maintainers:
  - name: Waldemar Quevedo
    github: https://github.com/wallyqs
    email: wally@nats.io
  - name: Colin Sullivan
    github: https://github.com/ColinSullivan1
    email: colin@nats.io
  - name: rchenzheng
    github: https://github.com/rchenzheng
icon: https://nats.io/img/nats-icon-color.png
