apiVersion: v2
appVersion: 0.14.2
description: A Helm chart for NACK
name: nack
keywords:
- nats
- jetstream
- cncf
version: 0.25.2
maintainers:
- email: info@nats.io
  name: The NATS Authors
  url: https://github.com/nats-io
icon: https://nats.io/img/nats-icon-color.png
