apiVersion: v2
name: nack
version: 0.33.1
appVersion: 0.22.1
description: A Helm chart for NACK - NATS Controller for Kubernetes
keywords:
- nats
- jetstream
- cncf
maintainers:
- email: info@nats.io
  name: The NATS Authors
  url: https://github.com/nats-io
icon: https://nats.io/img/nats-icon-color.png
