{{ if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "nats.name" . }}
  {{- if .Values.exporter.serviceMonitor.namespace }}
  namespace: {{ .Values.exporter.serviceMonitor.namespace }}
  {{- else }}
  {{- if .Values.exporter.serviceMonitor.labels }}
  labels:
    {{ .Values.exporter.serviceMonitor.labels }}
  {{- end }}
  {{- if .Values.exporter.serviceMonitor.annotations }}
  annotations:
    {{ .Values.exporter.serviceMonitor.annotations }}
  {{- end }}
spec:
  endpoints:
  - port: metrics
  {{- if .Values.exporter.serviceMonitor.path }}
    path: {{ .Values.exporter.serviceMonitor.path }}
  {{- end }}
  {{- if .Values.exporter.serviceMonitor.interval }}
    interval: {{ .Values.exporter.serviceMonitor.interval }}
  {{- end }}
  {{- if .Values.exporter.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.exporter.serviceMonitor.scrapeTimeout }}
  {{- end }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: {{ template "nats.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{- end }}
