metadata:
  labels:
    {{- include "nats.labels" $ | nindent 4 }}
  annotations:
    {{- if .Values.podTemplate.configChecksumAnnotation }}
    {{- $configMap := include "nats.loadMergePatch" (merge (dict "file" "config-map.yaml" "ctx" $) $.Values.configMap) }}
    checksum/config: {{ sha256sum $configMap }}
    {{- end }}
spec:
  {{- if .Values.reloader.enabled }}
  shareProcessNamespace: true
  {{- end }}

  containers:
  # nats
  {{- $nats := dict }}
  {{- with .Values.container }}
  {{- $nats = include "nats.loadMergePatch" (merge (dict "file" "stateful-set/nats-container.yaml" "ctx" $) .) | fromYaml }}
  - {{ toYaml $nats | nindent 4 }}
  {{- end }}
  # reloader
  {{- with .Values.reloader }}
  {{- if .enabled }}
  - {{ include "nats.loadMergePatch" (merge (dict "file" "stateful-set/reloader-container.yaml" "ctx" (merge (dict "natsVolumeMounts" $nats.volumeMounts) $)) .) | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.promExporter }}
  {{- if .enabled }}
  - {{ include "nats.loadMergePatch" (merge (dict "file" "stateful-set/prom-exporter-container.yaml" "ctx" $) .) | nindent 4 }}
  {{- end }}
  {{- end }}

  volumes:
  # nats config
  - name: config
    configMap:
      name: {{ .Values.configMap.name }}
  # PID volume
  {{- if .Values.reloader.enabled }}
  - name: pid
    emptyDir: {}
  {{- end }}
  # TLS secrets
  {{- range $protocol := list "nats" "leafnode" "websocket" "mqtt" "cluster" "gateway" }}
  {{- $configProtocol := get $.Values.config $protocol }}
  {{- if and (or (eq $protocol "nats") $configProtocol.enabled) $configProtocol.tls.enabled $configProtocol.tls.secretName }}
  - name: {{ $protocol }}-tls
    secret:
      secretName: {{ $configProtocol.tls.secretName | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.podTemplate.topologySpreadConstraints }}
  topologySpreadConstraints:
  {{- range $k, $v := . }}
  - {{ merge (dict "topologyKey" $k "labelSelector" (dict "matchLabels" (include "nats.selectorLabels" $ | fromYaml))) $v | toYaml | nindent 4 }}
  {{- end }}
  {{- end}}
