apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSet.name }}
  labels:
    {{- include "nats.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nats.selectorLabels" $ | nindent 6 }}
  {{- if .Values.config.cluster.enabled }}
  {{- if and .Values.config.jetstream.enabled (lt (int .Values.config.cluster.replicas) 2) }}
  {{- fail "cluster replicas must be >= 2 when jetstream is enabled" }}
  {{- end }}
  replicas: {{ .Values.config.cluster.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  serviceName: {{ .Values.headlessService.name }}
  podManagementPolicy: Parallel
  template:
    {{- with .Values.podTemplate }}
    {{ include "nats.loadMergePatch" (merge (dict "file" "stateful-set/pod-template.yaml" "ctx" $) .) | nindent 4 }}
    {{- end }}
  volumeClaimTemplates:
  {{- with .Values.config.jetstream }}
  {{- if and .enabled .fileStore.enabled .fileStore.pvc.enabled }}
  {{- with .fileStore.pvc }}
  - {{ include "nats.loadMergePatch" (merge (dict "file" "stateful-set/jetstream-pvc.yaml" "ctx" $) .) | nindent 4 }}
  {{- end }}
  {{- end }}
    {{- end }}
  {{- with .Values.config.resolver }}
  {{- if and .enabled .pvc.enabled }}
  {{- with .pvc }}
  - {{ include "nats.loadMergePatch" (merge (dict "file" "stateful-set/resolver-pvc.yaml" "ctx" $) .) | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
